import { NextPage } from 'next';
import Head from 'next/head';

const HomePage: NextPage = () => {
 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name='description' content='Generated by create next app' />
    <meta name='viewport' content='width=device-width, initial-scale=1' />
    <link rel='icon' href='/favicon.ico' />
   </Head>
   <main>
    <h1>Jiro</h1>
   </main>
  </>
 );
};

export default HomePage;
